stages:
    - deploy

deploy_be:
    stage: deploy
    image: node:latest
    tags:
        - hva
    only:
        refs:
            - staging
        changes:
          - "server/**/*"
    script:
        - git branch -D splitting-be || true
        - git remote rm heroku-be-app || true
        - git remote add heroku-be-app https://heroku:$HEROKU_API_KEY@git.heroku.com/stb-5-be-app-staging.git || true
        - git subtree split --prefix server -b splitting-be
        - git push --force heroku-be-app splitting-be:master

deploy_fe:
    stage: deploy
    image: node:latest
    tags:
        - hva
    only:
        refs:
            - staging
        changes:
          - "client/**/*"
    script:
        - git branch -D splitting-fe || true
        - git remote rm heroku-fe-app || true
        - git remote add heroku-fe-app https://heroku:$HEROKU_API_KEY@git.heroku.com/stb-5-fe-app-staging.git || true
        - git subtree split --prefix client -b splitting-fe
        - git push --force heroku-fe-app splitting-fe:master
